%% DL-NOMA-CSK System - Two-Vehicle DNN Training
%
% File: train_dnn.m
%
% Description:
%   Trains a single DNN-based demodulator for the DL-NOMA-CSK system.
%   The same DNN is used at each SIC stage during online testing.
%
% DNN Architecture:
%   Input (2 x beta) -> Conv1D(32, k=3) -> BN -> ReLU
%                     -> Conv1D(32, k=6) -> BN -> ReLU
%                     -> Multi-Head Self-Attention (8 heads, d_h=64)
%                     -> Global Average Pooling
%                     -> FC(64) -> ReLU -> Dropout(0.2)
%                     -> FC(2) -> Softmax -> Classification
%
% Input:
%   dataset/train_data_2user.mat  (generated by generate_dataset.m)
%
% Output:
%   models/trained_net_2user.mat  (trained network + params)
%
% Dependencies:
%   - MATLAB R2023b or later 
%   - Deep Learning Toolbox
%
% Last Updated: 2025


%% ====================== Load Dataset ======================
clc; clear; close all;

dataDir  = 'dataset';
modelDir = 'models';

if ~exist(modelDir, 'dir')
    mkdir(modelDir);
end

dataPath = fullfile(dataDir, 'train_data_2user.mat');
if ~exist(dataPath, 'file')
    error('Dataset not found: %s\nRun generate_dataset.m first.', dataPath);
end

fprintf('Loading dataset: %s ...\n', dataPath);
loaded = load(dataPath);

trainData   = loaded.trainData;
trainLabels = loaded.trainLabels;
valData     = loaded.valData;
valLabels   = loaded.valLabels;
params      = loaded.params;

fprintf('  Training samples:   %d\n', length(trainData));
fprintf('  Validation samples: %d\n', length(valData));
fprintf('  Bit-0 ratio (train): %.1f%%\n', ...
    sum(trainLabels == '0') / length(trainLabels) * 100);
fprintf('\n');

% Shuffle training data
shuffleIdx  = randperm(length(trainData));
trainData   = trainData(shuffleIdx);
trainLabels = trainLabels(shuffleIdx);

%% ====================== Hyperparameters ======================

numFilters  = 32;       % Convolutional filters (n)
kSize       = 3;        % Kernel size (k_size)
numHeads    = 8;        % Attention heads (h)
attDim      = 64;       % Attention dimension (d_h)
fcHidden    = 64;       % First FC layer neurons
dropRate    = 0.2;      % Dropout rate
numClasses  = 2;        % Binary classification {0, 1}

maxEpochs     = 20;
miniBatchSize = 1024;
initialLR     = 1e-3;
lrDropFactor  = 0.1;
lrDropPeriod  = 10;
valPatience   = 20;
valFrequency  = 30;

%% ====================== Build DNN Architecture ======================

fprintf('Building DNN architecture...\n');

layers = [
    sequenceInputLayer(2, 'Normalization', 'zscore', 'Name', 'input')
    
    convolution1dLayer(kSize, numFilters, ...
        'Padding', 'same', 'Name', 'conv1')
    batchNormalizationLayer('Name', 'bn1')
    reluLayer('Name', 'relu1')
    
    convolution1dLayer(2 * kSize, numFilters, ...
        'Padding', 'same', 'Name', 'conv2')
    batchNormalizationLayer('Name', 'bn2')
    reluLayer('Name', 'relu2')
    
    selfAttentionLayer(numHeads, attDim, 'Name', 'mhsa')
    
    globalAveragePooling1dLayer('Name', 'gap')
    
    fullyConnectedLayer(fcHidden, 'Name', 'fc1')
    reluLayer('Name', 'relu3')
    dropoutLayer(dropRate, 'Name', 'dropout')
    
    fullyConnectedLayer(numClasses, 'Name', 'fc_out')
    softmaxLayer('Name', 'softmax')
    classificationLayer('Name', 'output')
];

fprintf('\nNetwork Layers:\n');
disp(layerGraph(layers).Layers);
fprintf('\n');

%% ====================== Training Options ======================

options = trainingOptions('adam', ...
    'ExecutionEnvironment',   'auto', ...
    'MaxEpochs',              maxEpochs, ...
    'MiniBatchSize',          miniBatchSize, ...
    'InitialLearnRate',       initialLR, ...
    'LearnRateSchedule',      'piecewise', ...
    'LearnRateDropFactor',    lrDropFactor, ...
    'LearnRateDropPeriod',    lrDropPeriod, ...
    'GradientThreshold',      1, ...
    'Shuffle',                'every-epoch', ...
    'ValidationData',         {valData, valLabels}, ...
    'ValidationFrequency',    valFrequency, ...
    'ValidationPatience',     valPatience, ...
    'OutputNetwork',          'best-validation-loss', ...
    'Verbose',                true, ...
    'VerboseFrequency',       50, ...
    'Plots',                  'none');

%% ====================== Train Network ======================

fprintf('Starting training...\n');
fprintf('  Epochs: %d | Batch: %d | LR: %.1e\n\n', ...
    maxEpochs, miniBatchSize, initialLR);

trainStartTime = tic;
net = trainNetwork(trainData, trainLabels, layers, options);
trainElapsed = toc(trainStartTime);

fprintf('\nTraining complete in %.1f seconds.\n\n', trainElapsed);

%% ====================== Evaluate on Validation Set ======================

fprintf('Evaluating on validation set...\n');
valPred = classify(net, valData, 'MiniBatchSize', miniBatchSize);
valAcc  = sum(valPred == valLabels) / numel(valLabels) * 100;
fprintf('  Validation accuracy: %.2f%%\n\n', valAcc);

%% ====================== Save Trained Model ======================

savePath = fullfile(modelDir, 'trained_net_2user.mat');

trainInfo = struct();
trainInfo.totalTrainSamples = length(trainData);
trainInfo.totalValSamples   = length(valData);
trainInfo.valAccuracy       = valAcc;
trainInfo.trainTime         = trainElapsed;
trainInfo.hyperparams       = struct( ...
    'numFilters',    numFilters, ...
    'kSize',         kSize, ...
    'numHeads',      numHeads, ...
    'attDim',        attDim, ...
    'fcHidden',      fcHidden, ...
    'dropRate',      dropRate, ...
    'maxEpochs',     maxEpochs, ...
    'miniBatchSize', miniBatchSize, ...
    'initialLR',     initialLR);

save(savePath, 'net', 'params', 'trainInfo', '-v7.3');

fprintf('========================================\n');
fprintf('  Model saved to: %s\n', savePath);
fprintf('  Validation accuracy: %.2f%%\n', valAcc);
fprintf('========================================\n');